services:
  gameserver:
    build: ./services/gameserver
    ports:
      - "8080:8080"  # Also allow direct port 8080 access for Replit compatibility
    volumes:
      - ./services/gameserver:/app
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/sectorwars}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - JWT_SECRET=${JWT_SECRET:-dev-secret-key}
      - DEBUG=${DEBUG:-true}
      - CLIENT_ID_GITHUB=${CLIENT_ID_GITHUB:-mock_github_client_id}
      - CLIENT_SECRET_GITHUB=${CLIENT_SECRET_GITHUB:-mock_github_client_secret}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8080}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - DEV_ENVIRONMENT=${DEV_ENVIRONMENT:-local}
      - CODESPACE_NAME=${CODESPACE_NAME:-}
    restart: unless-stopped
    networks:
      - sectorwars-network

  player-client:
    build: ./services/player-client
    ports:
      - "3000:3000"
    volumes:
      - ./services/player-client:/app
      - /app/node_modules
    environment:
      - API_URL=http://gameserver:8080
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped
    depends_on:
      - gameserver
    networks:
      - sectorwars-network

  admin-ui:
    build: ./services/admin-ui
    ports:
      - "3001:3001"
    volumes:
      - ./services/admin-ui:/app
      - /app/node_modules
    environment:
      - API_URL=http://gameserver:8080
      - PORT=3001
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped
    depends_on:
      - gameserver
    networks:
      - sectorwars-network

networks:
  sectorwars-network:
    driver: bridge