services:
  gameserver:
    build: ./services/gameserver
    ports:
      - "8080:8080"  # Also allow direct port 8080 access for Replit compatibility
    volumes:
      - ./services/gameserver:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - sectorwars-network

  player-client:
    build: ./services/player-client
    ports:
      - "3000:3000"
    volumes:
      - ./services/player-client:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - API_URL=http://gameserver:8080  # This is a container-specific setting
    restart: unless-stopped
    depends_on:
      - gameserver
    networks:
      - sectorwars-network

  admin-ui:
    build: ./services/admin-ui
    ports:
      - "3001:3001"
    volumes:
      - ./services/admin-ui:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - API_URL=http://gameserver:8080  # This is a container-specific setting
      - PORT=3001  # This is a container-specific setting
    restart: unless-stopped
    depends_on:
      - gameserver
    networks:
      - sectorwars-network

networks:
  sectorwars-network:
    driver: bridge