"""add_deleted_column_to_oauth_accounts

Revision ID: 661c9a732e7c
Revises: 77cbe1cafa12
Create Date: 2025-05-11 17:37:47.084138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661c9a732e7c'
down_revision = '77cbe1cafa12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accounts', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_accounts', 'deleted')
    # ### end Alembic commands ###